### ISSUE TITLE
Gui Error when executing /pwp gui.

### ISSUE THREAD

**Issue by ghost** [heretere/hpwp#1]
Hello ! I recently purchased Per World Plugins. Everything works, the plugin launches without error.
However, when I run the command **/pwp gui** to open the gui, the plugin tells me that an error has occurred.
So I went to the console and here is the error: https://pastebin.com/XgEWzLTB

More information:
Server: iSpigot 2.2-SNAPSHOT (Latest - 1.8.8 PaperSpigot fork)
Per World Plugins: 1.3.0 (Latest)

I can do tests if necessary. I want to do everything to help fix this bug.
If you need more information, you can ask me!
Thanks!

**Comment by heretere** [comment]
Thanks for bringing this to my attention. I'll make sure to post an update soon resolving this issue.

**Comment by heretere** [comment]
Fixed issue in bbfe633e5e637297bef52ac6f8a7afad692ccb32

https://www.spigotmc.org/resources/per-world-plugins.88018/update?update=408243
